### ISSUE TITLE
A few caveats

### ISSUE THREAD

**Issue by glubsy** [ppixiv/ppixiv#1]
Thanks for sharing this wonderful user script. Very nicely done, clear code and clear comments. The work of a professional for sure.

A few caveats from my point of view, just as user feedback:

* The thumbnails are too zoomed in, compared to vanilla pixiv, there is less to see at first glance, which is not ideal for browsing efficiently. It would be good to have the option to disable any processing on the thumbnail and use the ones provided by pixiv directly instead. 

* When viewing a single item after clicking on it in the gallery view mode, the script goes back to the first picture found in the gallery. This is not ideal and a bit confusing. It would be nice to either 
1) block the browsing at the last picture in the set of pictures being currently displayed 
2) have the ability to go back to the previously displayed set of pictures in case we went back to that first set found in the gallery
3) continue the slide show resuming from the next item in the gallery view

* When requesting regular pixiv page (instead of the user script's page) by clicking "return to pixiv", this doesn't stay that way once the user browses to the next page in the (regular pixiv) gallery. It would be nice if this could stick until the user script is manually called again by clicking on its icon in the top left corner. Maybe using cookies would make this possible? I wouldn't have to use regular pixiv if the thumbnails were not cropped. 

* Date displayed should display the actual date (in a tooltip maybe) along with "3 months ago" for example. Precision is always preferred.

* Displaying the current page of the set out of the total would be nice. I often wonder which page I'm currently viewing (i.e. 1234546_p2.jpg). Maybe hovering the mouse cursor over the thumbnails at the bottom of the screen could display that information in a tooltip?

* Add the ability to download the "12345678_ugoira1920x1080.zip" file, instead of just the encoded MKV. That's what originally drew me to this script, I was looking for a way to set the referrer automatically in order to download the ZIP file, and your script allows to do that by looking for it in the dev tools. Would be handy to have this available in the UI directly.

I'd like to express my sincere gratitude for sharing this script.
I don't expect any of these suggestions to be actually implemented, but I thought some user feedback would have some value anyway.
Thanks for your time!

**Comment by ppixiv** [comment]
Thanks for the feedback.  I'll look at it all, but to just reply to some for now:

The current release gives more control over the thumbnail size.  I like big thumbnails with a maximized window, but you can make them smaller.  It limits the number of columns it shows to try to avoid configurations that might hammer the site in order to fill up the screen (trying to be polite), but you should be able to see a good amount.  You can also turn off the zoom effect in the options dropdown.  They'll still be cropped to a square (but so are most Pixiv layouts).

I'm not sure if it's the case you're seeing., but I pushed a fix for navigating to the search with the UI buttons not restoring correctly (no build update yet).

Usually I use "return to pixiv" if if I want to access something this doesn't support (eg. leaving a comment), and I just middle-click the button into a new tab and then close it when I'm done.  Maybe just turn off the script if you want it off for a while?  At least with TamperMonkey you can do that in a couple clicks.

FYI, the page number is also now in the URL,

**Comment by glubsy** [comment]
Thanks!

Regarding the thumbnail "size", I was only referring to the cropping of the image, not the dimensions of the thumbnail itself. It's a bit cumbersome to have to wait for the panning to see the entire thumbnail (and decide whether or not it's worth clicking on it). Might be troublesome since pictures are often not squares but rectangles, but perhaps that can be easily worked around?

Anyway, turns out today (!?) Pixiv changed their page layouts and galleries now look almost exactly like your script! That was unexpected and very timely. The thumbnails actually look the same in their new layout, except there is no panning. So your script has an advantage here. ;-)

Regarding the new popup menu that appears after right clicking on a picture view (with zoom 2x, 4x, 8x): this blocks the regular browser menu, which is not ideal when trying to save a picture (or other  functions from other plugins), since "save as" is not accessible anymore. Perhaps it would be best to glue that new menu below the already existing one in the top left hand corner?

**Comment by ppixiv** [comment]
The cropping is to allow the page to be packed cleanly, without different aspect ratios causing a bunch of empty space.  I usually find that the cropped area is enough to decide whether to open an image or not, without actually needing to see the rest (the panning just makes it possible).

(Odd, the page layout changed for me a week or two ago.  It doesn't seem like they're doing staged rollouts, the script probably wouldn't still work with the old layout...)

You can hold shift while right clicking to get back to the regular context menu.

**Comment by glubsy** [comment]
> You can hold shift while right clicking to get back to the regular context menu.

I'm using Chromium, and no matter the key combination I try, I cannot get the regular context menu.
Can't use Firefox sadly, it just doesn't work properly on my system anymore.

**Comment by ppixiv** [comment]
I'm not sure what's wrong (works for me in Chrome 69 with Win10).  If you want to poke at it, look at onmousedown in popup_context_menu (widgets.js), which checks e.shiftKey.  (In Chrome it'll show up as userscript.html in the sources panel, so the debugger works, you just have to wade through the big combined script to find it.)

**Comment by glubsy** [comment]
I'm using Chromium "version 69.0.3497.100 (Official Build) Arch Linux" (from the official Arch Linux repository). 
At first, I noticed that left clicking in the developer tools and then doing the shift+right click on the displayed picture actually works the first time only, subsequent tries don't work anymore.

Anyway I found what caused the problem: another add-on ([linkclump](https://chrome.google.com/webstore/detail/linkclump/lfpjkncokllnfokkgpkobnkbkmelfefj)) was catching the mousedown event + shift or something, and probably stopped propagation (I don't know javascript very well, sorry).   

Suggestion: how about making this custom menu active only on shift+right click instead?

**Comment by ppixiv** [comment]
That would be too clunky for me, since the popup menu is meant for quick navigation, but I added an option to reverse the shift button behavior.

**Comment by ppixiv** [comment]
The thumbnail strip became annoying when zoom locking was added, since you'd click and pan around, then the thumbs would often appear when you released the mouse button because the mouse ended up over it while you were dragging.  I've been meaning to add a cursor to the manga view to make it easier to tell where you are.

**Comment by ppixiv** [comment]
The "return to Pixiv" button is now stored in the session, which means it'll stay disabled in that one tab, but not affect other tabs.  It seems to work pretty well, so you can switch it off in one tab without it coming back as soon as you click anything, but not have it become disabled it in other tabs.

**Comment by glubsy** [comment]
That is awesome! Everything seems to work very well on my side. The new changes are nice. Thank you!

**Comment by ppixiv** [comment]
Going to close this, since it's really old and I think I've done everything that feels like it fits.  But, if you're still around and you'd like me to take another look at something in particular, go ahead and reopen or open another ticket.
