### ISSUE TITLE
Data format change on Pixiv to two "meta" tags broke script

### ISSUE THREAD

**Issue by Phenrei** [ppixiv/ppixiv#10]
I don't have the full setup on hand to make a proper pull request, but I was able to adapt to a change on pixiv's part to the page code. Instead of needing to take apart scripts, the data is embedded in JSON form into the "content" part of two meta tags, "meta-global-data" and "meta-preload-data" which can be parsed by the rest of the code as-is. 

In "get_global_init_data" the script just needs to do a single queryselector on "meta#meta-preload-data", and return its "content" data through eval into the JSON parse, and similar in "get_pixiv_data" for "meta#meta-global-data".

The "pixiv" part of the data requires a slight change elsewhere due to different JSON formatting:

`this.init_global_data(pixiv.context.token, pixiv.user.id, pixiv.user.premium, pixiv.user.mutes, pixiv.user.explicit);`
to
`this.init_global_data(pixiv.token, pixiv.userData.id, pixiv.userData.premium, pixiv.mute, pixiv.userData.adult);`

I had simply commented out blocks checking for validity of data, which would need updating.

**Comment by ppixiv** [comment]
It looks like it happens on /new_illust.php.  (They don't change their pages in any consistent way, they just change them one by one randomly.  I don't know how they maintain anything...)  I'll take a look.  Thanks!

**Comment by ppixiv** [comment]
Have you seen any pages that actually have meta-preload-data filled in?  I only see this on /new_illust.php, and that data is empty on that page (just a timestamp value).  If no pages are using that I'll leave it unused for now, since I don't have anything to test against.

**Comment by ppixiv** [comment]
Aha, the actual illustration pages use it.

**Comment by ppixiv** [comment]
I've pushed r62, let me know if that works for you.
