### ISSUE TITLE
Exit pictures

### ISSUE THREAD

**Issue by satyrsaw** [ppixiv/ppixiv#106]
when on home screen and select a picture, i noticed that pressing ESC doesn't exit the picture. It only exits full screen. I really got stuck on the pictures. It took like 15m to discover that right clicking has the exit button. That is SOOOOO inconvenient and not really user friendly. Let me ESC to exit the picture, please. Thanks for listening to my ted talk .

**Comment by ppixiv** [comment]
It's just browser back (I have it bound to my mouse's "tilt mousewheel left" button), the context menu button is just there to allow navigating with only the mouse for people who haven't done that.  But sure, r240.
