### ISSUE TITLE
Context menu should not require holding down RMB

### ISSUE THREAD

**Issue by nc7s** [ppixiv/ppixiv#108]
which is tiring when going through a lot of items. And weird; context menus just don't behave that way, generally.

I'm happy to implement the change, but have to first go through the codebase. Meanwhile, a pointer would help.

**Comment by nc7s** [comment]
Hmm, didn't know the "context" menu at the top left corner. It does what's needed and doesn't need holding.

**Comment by ppixiv** [comment]
Right mouse navigation predates the context menu by a long time: RMB-LMB click toggles zoom and RMB-wheel zooms in and out, to allow navigation with only the mouse.  The context menu was designed to not interfere with this.  It also works better than a stock Windows menu for common uses, like quickly seeing if I've bookmarked an image already, or bookmarking an image and then opening the artist's post list without having to reopen the menu each time.
