### ISSUE TITLE
Background glitch on pixiv's default light theme

### ISSUE THREAD

**Issue by Theonormal** [ppixiv/ppixiv#110]
As shown below, and despite dark theme not having been turned on, the backgrounds for image pages or individual work pages remain black. The issue is absent in artist pages or pixiv's homepage. Issue not present when ppixiv script is turned off.
<img width="1439" alt="Screenshot 2024-08-25 at 12 02 15 PM" src="https://github.com/user-attachments/assets/7d901ff8-3791-42c6-80a3-15d32863f821">
screen recording: https://files.catbox.moe/9ar72b.mp4

Using macOS Sonoma, Floorp browser, violentmonkey script manager.

**Comment by ppixiv** [comment]
Try r241.

**Comment by Theonormal** [comment]
> Try r241.

works great now, issue gone
