### ISSUE TITLE
Need directions on how to build or run code

### ISSUE THREAD

**Issue by microwaver24** [ppixiv/ppixiv#111]
I am not a web dev, but I do work in software. Maybe I am missing some basic knowledge about how this kind of repo can be built/run?

I made a fork and I am trying to run it. Or I guess it would be fine if I could just export to a single greasemonkey script and paste it into the script editor.

I have python 3. I found the readme in the vview directory so I did `pip install aiohttp pywin32 natsort pillow pycairo libsass`.

If I navigate to the repo directory and do `python debug.py` it fails with a not very helpful error. Similar issue but different error if I go to the build directory and try `python build_ppixiv.py`.  It would be rad if the readme at least had a command line for how I am supposed to run this. Or maybe there is another setup step I don't know about?

**Comment by ppixiv** [comment]
Try:

python3.12 -m vview.build.build_ppixiv

from the top directory.  You can ignore most of the vview directory, you don't need most of it to build just the Pixiv script.

**Comment by microwaver24** [comment]
I got it to build after a bit of messing around. There is another step I had to do. Add a git tag to my fork of the repo. I just added a tag to my commit that was `r1` and then it stopped complaining about the release version.
