### ISSUE TITLE
I am a new user, I have some questions.

### ISSUE THREAD

**Issue by duradara** [ppixiv/ppixiv#115]
Is there any way to add a back and forward arrows to galleries with more than one image instead of using arrow keys? Something like this.
![1](https://github.com/user-attachments/assets/87f79921-4c05-4141-836f-90e25f1df531)

  
Also is there any way to make the right click menu open when I right click and close when I right click again instead of having to hold it?

Sorry if my English is bad.

**Comment by ppixiv** [comment]
Try using the mousewherel to navigate between images, it's a lot more convenient than the keyboard.  The popup menu is built around the press-and-hold behavior, such as right-left click to toggle zoom, and right-click-mousewheel to zoom in and out (these actually predate there being a popup menu in the first place and the menu was designed around it).
