### ISSUE TITLE
hold right click to open context menu, and also other things

### ISSUE THREAD

**Issue by srishak34** [ppixiv/ppixiv#16]
its fancy. i'd be honest here it really is. it may have been exaggerating to say but can you just make it "right click" to do it? also when you click on image, can you not in auto just right zoom in into picture? also that scrolling feature just pissed me off, i understand if you wanted to try to make a single-page web experience, but in terms of user experience, it pissed me the *** off, also whats up with clicking the image only to return to search i need to literally click esc button or do it in STYLE (frea*ing hold right click and left click on return to search button) are there seriously no option to just do it in the OLD way? i wanted my "open link in new tab" BACK! i wanted my "1 click on love button to bookmark" BACK! i wanted when i bookmarked picture in discovery page, it automatically shows 4 or less picture related works! also why heck when i click on similar illusts button i cant go return to search ? why the heck not? 
edit: also put the R18 icon on image -_-

the whole thing is nice don't get me wrong, the picture loads so quickly, the UI is very nice and im so glad it has a dark theme and im grateful for it. nice work. good job. excellent work! you've done so much with improving the whole thing pixiv is lacking, but maybe except for those things i mentioned.

but seriously though back to the very top, its fre**ing annoying!

**Comment by srishak34** [comment]
the whole thing seemed so silly, -_- im closing it up.

**Comment by ppixiv** [comment]
Happy for constructive feedback, but rants not so much...

**Comment by ppixiv** [comment]
This is pretty hard to read (too much yelling and swearing...), but you can open the browser right click menu by holding shift while right-clicking, at least in Firefox and Chrome.  Middle clicking links also opens links in a new tab (like any page).

If you're in Chrome you can also enable "Hold shift to open context menu" in settings, which reverses it (right click opens the regular menu).  Firefox doesn't support that.

If you click "Zoom to full" in the context menu, future images will zoom to full by default until you zoom back out.  If you're on a regular mouse, you can also zoom in and out quickly by holding the right mouse button (open the context menu) and moving the mousewheel.

**Comment by srishak34** [comment]
I am really sorry for my excessive yelling and swearing, it just that i got
a bit frustrated with how superior this (add-on?) and yet it ignores some
of the good points of pixiv. i hope i can delete this issue, its so
embarrassing to type. I am really, really sorry about all of this.
