### ISSUE TITLE
changing the update path

### ISSUE THREAD

**Issue by raingart** [ppixiv/ppixiv#20]
> The most recent version can be installed here.

why not use then?
`// @updateURL  https://s3.amazonaws.com/ppixiv/ppixiv.user.js`

**Comment by ppixiv** [comment]
The update URL is set automatically to wherever you installed it from, and these tags is generally not used.  It's just something that needs to be changed if it's being installed from somewhere else, like debug builds, and it's a big inconvenience for forks.

**Comment by raingart** [comment]
[openuserjs](https://openuserjs.org/) exactly uses it. Maybe you also need to publish the script there too
