### ISSUE TITLE
Feature: Expand thumbnail instead of panning while hovering

### ISSUE THREAD

**Issue by XDcedar** [ppixiv/ppixiv#21]
I've been using ppixiv for a long time and the thumbnail layout is smooth and delightful. Really good job!
However panning feature did little help when I hope to make a quick glance at the whole pic without click it - I cannot see character's face and feet at the same time and the pic keeps swinging up and down (or, left and right). Would it be possible to add a new feature that makes thumbnail box expand to show full picture? An example is yande.re (while holding Shift key).
Thank you and best wishes!

**Comment by ppixiv** [comment]
(Oops, missed this)

I implemented that feature on yande.re too, actually (long ago), but I haven't really found a way to fit something like that in this UI very well.  It's just tricky to make it fit cleanly with the way the thumbnails work.

**Comment by XDcedar** [comment]
I never expect to meet a yande.re developer here for real! Thank you for developing that booru site!
If there is a technical Issue, it's ok then. I'll try to adapt to it. (Still wish this feature could be added sometime in the future though. non-stop panning makes me kinda "nervous", I don't know why...)

**Comment by ppixiv** [comment]
I tried some other things, like having the pan follow the mouse (mouse at the top of thumbnail = panned to the top), but none of it worked very well.  I'll close this since it probably won't be implemented, but I'll keep this in mind in case I get ideas in the future.
