### ISSUE TITLE
Feature Request: Add Fanbox button (If available)

### ISSUE THREAD

**Issue by yul-oh895** [ppixiv/ppixiv#23]
My request is to make a Fanbox button on the top bar of an artist page where you can press it and sends you to the Fanbox page if the artist has both linked.

Currently If I find an artist I might be interested in supporting via Fanbox, I have to disable ppixiv, open the Fanbox page in a new tab and re-enable ppixiv.

**Comment by ppixiv** [comment]
15240ad74 fixes links in the description not being loaded.

**Comment by yul-oh895** [comment]
Thank you for the quick update on #24.

This is a separate issue as I meant the native Fanbox button on Pixiv which is this one:
![08-22_16-48-31](https://user-images.githubusercontent.com/64549167/130530311-f8492366-b03e-452b-b5b8-589fdba2df2d.png)

A button showing this address was not been available on the artist top bar unless they added it as an alternative link. I wanted to know if its possible to add it as an extra button so it can be easier to open their Fanbox.

**Comment by yul-oh895** [comment]
Hi @ppixiv sorry for reopening this older issue.

The new shortcut/link has been working with all profiles I have seen so far which I appreciate it a lot. For some there is only one artist so far where I noticed the link doesn't show up. Would it be possible for you to review and check this?

[artist page](https://www.pixiv.net/en/users/1423658)

Thanks

**Comment by ppixiv** [comment]
Try r116.  The maximum number of links from the user's profile was being reached, which is to keep the UI from going crazy if somebody spams a bunch of URLs.  I've reworked it to only limit links from the profile text, so it won't prevent the Fanbox link from being included (it comes from a different place but is handled in the same way).

**Comment by yul-oh895** [comment]
Thanks! It is working great.
