### ISSUE TITLE
opening with the left mouse button of the author does not work

### ISSUE THREAD

**Issue by raingart** [ppixiv/ppixiv#26]
![Screenshot from 2021-09-12 11-57-24](https://user-images.githubusercontent.com/13064767/132981602-26cc5c3d-b6d3-496b-8c8e-b970fbbd2f64.png)

Works with middle button only

**Comment by ppixiv** [comment]
It's working for me in r98 in Chrome.  Are you opening the menu with right-click or holding ctrl?  Does anything show up in the console when you click (press F12)?

**Comment by raingart** [comment]
archlinux chromium 89.0.4389.82 (Official Build) (64-bit)
on the image I hold down the right button and with the left open the author by avatar. Everything works up to version 97
in 98, the link does not open when clicked. There are no errors in the console

**Comment by raingart** [comment]
ex. https://drive.google.com/file/d/1t4mqmvH5uyiNzYy7erKh-WWu9v0pi6xk/view?usp=sharing

**Comment by raingart** [comment]
here problem 
https://github.com/ppixiv/ppixiv/blob/master/src/main_context_menu.js#L160-L162

**Comment by ppixiv** [comment]
Oh, the fix for that got committed with something unrelated that isn't pushed yet.  I'll split it out.  91e26d86f

**Comment by ppixiv** [comment]
Try updating to r99.

**Comment by raingart** [comment]
also add dependencies for build
I are too lazy to understand, not many will be able to do it.
Better description of how to do it

![Screenshot from 2021-09-12 17-22-54](https://user-images.githubusercontent.com/13064767/132991528-e2073702-38d8-4ec3-9ce9-5a34e7fb124f.png)
![Screenshot from 2021-09-12 17-21-18](https://user-images.githubusercontent.com/13064767/132991529-98e909cd-3eb1-420c-aa94-34ae311b793c.png)

**Comment by ppixiv** [comment]
It's a Python 2 script, but you're running Python 3.  I can update it in a bit.
