### ISSUE TITLE
Feature Request: Single Image Download on multi-image sets

### ISSUE THREAD

**Issue by bgiesing** [ppixiv/ppixiv#28]
Currently there's only one download button that either downloads the image on single image posts, a ZIP on multi-image works, or a video file on animations. Sometimes you might want to download only one single image of a multiple image work and it's currently really hard to do that with this script enabled (you either have to download the ZIP, extract the one single image, rename it to match the format usually used for single image downloads, and delete all the other images you don't want to keep OR revert back to standard Pixiv and right click > Save As).

It would be super handy on multi-works if you could add an extra button to JUST download the current visible image if that's all you want.

**Comment by ppixiv** [comment]
I've added a separate button for this in r100.

FWIW, you can also shift-right-click and use the regular "save image as", though of course that doesn't give a good default filename.
