### ISSUE TITLE
Latest works from followed user page blank.

### ISSUE THREAD

**Issue by tlombard2000** [ppixiv/ppixiv#29]
I just tried checking my following artists (https://www.pixiv.net/bookmark_new_illust.php#ppixiv) and the entire page was blank. This was the only page that this happened on. Specific artists and tag pages worked fine. I tested this on 3 different browsers (Firefox, Edge, Opera) just in case this was only my issue and it still happened so I feel it may not be just my issue? It was not doing this previously. Version r100 if it helps. If you need any more info, lmk! Thank you!

**Comment by tlombard2000** [comment]
Here are the errors. I got 2 of each of the ones below.

Uncaught (in promise) TypeError: element is null
- parse_document - _moz-extension://70934451-8eca-499e-9d5c-d03490658b88/ ppixiv for Pixiv.user.js#2:8153_
- finished_loading_illust - _moz-extension://70934451-8eca-499e-9d5c-d03490658b88/ ppixiv for Pixiv.user.js#2:7058_
- load_page_internal - _moz-extension://70934451-8eca-499e-9d5c-d03490658b88/ ppixiv for Pixiv.user.js#2:7031_
- _load_page_async - _moz-extension://70934451-8eca-499e-9d5c-d03490658b88/ ppixiv for Pixiv.user.js#2:6036_
- load_page - _moz-extension://70934451-8eca-499e-9d5c-d03490658b88/ ppixiv for Pixiv.user.js#2:5978_
- load_needed_thumb_data - _moz-extension://70934451-8eca-499e-9d5c-d03490658b88/ ppixiv for Pixiv.user.js#2:13362_
- set_data_source - _moz-extension://70934451-8eca-499e-9d5c-d03490658b88/ ppixiv for Pixiv.user.js#2:12838_
- set_current_data_source - _moz-extension://70934451-8eca-499e-9d5c-d03490658b88/ ppixiv for Pixiv.user.js#2:17289_


Uncaught (in promise) TypeError: element is null
- parse_document - _moz-extension://70934451-8eca-499e-9d5c-d03490658b88/ ppixiv for Pixiv.user.js#2:8153_
- finished_loading_illust - _moz-extension://70934451-8eca-499e-9d5c-d03490658b88/ ppixiv for Pixiv.user.js#2:7058_
- load_page_internal - _moz-extension://70934451-8eca-499e-9d5c-d03490658b88/ ppixiv for Pixiv.user.js#2:7031_
- _load_page_async - _moz-extension://70934451-8eca-499e-9d5c-d03490658b88/ ppixiv for Pixiv.user.js#2:6036_
- load_page - _moz-extension://70934451-8eca-499e-9d5c-d03490658b88/ ppixiv for Pixiv.user.js#2:5978_
- load_needed_thumb_data - _moz-extension://70934451-8eca-499e-9d5c-d03490658b88/ ppixiv for Pixiv.user.js#2:13362_
- window.VMin07lgkynn8/set active/< - _moz-extension://70934451-8eca-499e-9d5c-d03490658b88/ ppixiv for Pixiv.user.js#2:13118_


Also tried the last option, and it had the same outcome for me.

**Comment by tlombard2000** [comment]
Huh. I apologize as I never tried it on a different account, but it actually is 2 different looking pages. The account that is not working has the more updated UI version of the page, so that does appear to be why it was happening.

**Comment by ppixiv** [comment]
Try r101, let me know if it's working for you.
