### ISSUE TITLE
feature request, maybe?

### ISSUE THREAD

**Issue by d4r4ki4n** [ppixiv/ppixiv#3]
Would it be possible to implement a mute list feature for artists in ppixiv? I know Pixiv has their own mute, but they only give you 1 to use for free, and even if I paid I don't think only 500 would really cut it for my purposes. There are many unwanted artists that just clog up the discovery feature by virtue of tags alone.

I totally get if you don't want to risk pissing off Pixiv with it, it was just an idea I thought to be worth pitching to you. If not, being able to mute with the Pixiv option from within ppixiv would be great.

**Comment by ppixiv** [comment]
I've thought about adding mutes (especially for tags).  I don't think it's defensible for Pixiv to try to profit from people not wanting to see some content on there.  I'd want it to interface with the built-in muting if people are using it, though, so it's a bit tricky, and since I do have a premium account I just haven't spent much time trying to work it out...

**Comment by d4r4ki4n** [comment]
That's all pretty understandable to me. Well, I'm gonna keep using your script for as long as you maintain it so take your time on a solution that you think works best and I'll be grateful for it if and when it does arrive. In the meantime, I'll just suck it up and buy premium the next time I get frustrated at having to scroll past a hundred terrible works from the same artist.

**Comment by yaomtc** [comment]
I'd be satisfied with being able to mute "loli", "shota", and the Japanese equivalents, *especially* when it's suggestive or explicit. I feel like I shouldn't have to pay Pixiv for the privilege of not seeing fucked up - and possibly illegal - content. Maybe at some point I'll give in and get a premium account...

**Comment by ppixiv** [comment]
Try r126.  You can edit mutes from the preferences menu now.  It'll be saved locally instead of to your Pixiv account if you don't have premium, and use the Pixiv mute lists if you do.

**Comment by yaomtc** [comment]
Ah, so this only hides the images within the ppixiv interface, but it doesn't hide them from the site itself -- is there a way around that

**Comment by ppixiv** [comment]
Changing the site itself isn't really what I'm trying to do.  I think it would be really hard, since the site loads posts in a ton of different ways and the site markup itself is hard to interface with.

**Comment by yaomtc** [comment]
That is fair, I will try sticking to the ppixiv interface as much as possible then. Thank you.
