### ISSUE TITLE
Bookmarks icons incorrect / no bookmark and likes count.

### ISSUE THREAD

**Issue by yul-oh895** [ppixiv/ppixiv#31]
Hello, I noticed the Bookmarks are not working properly:

- The icons for bookmarks are backwards. This means that if you open the Pixiv artwork page it will show as if both Bookmarks are highlighted even if this is a new artwork that I have never Bookmarked. You can see an example here: 

![Untitled](https://user-images.githubusercontent.com/64549167/139385289-52a23d37-0b6c-41de-81c9-2aacbabe4b4e.png)

1. Shows the artwork details when the bookmark has not been added yet (but the icons are highlighted as if it was).
2. Shows the thumbnail of the artwork which confirms the bookmark has not been added yet.
3. Shows the artwork details after the bookmark was "added" (the icons are no longer highlighted).

- When adding a new artwork as private bookmark, it will save it instead as public bookmark instead. Pressing on the private bookmark icon or switching between public and private doesn't fix it. I need to manually do it through the normal Pixiv website.
- Also as you can see on this picture, the bookmark count and Like count are no longer displayed.

Let me know if you need more information from me.

Thank you for always keeping this script up to date and adding new features 👍

**Comment by ppixiv** [comment]
Should be fixed.  (I actually very rarely use that interface, I use the context menu for almost everything...)

**Comment by yul-oh895** [comment]
Thank you. It is working properly once again!
