### ISSUE TITLE
bug in linux / show contex menu

### ISSUE THREAD

**Issue by raingart** [ppixiv/ppixiv#33]
![Screenshot from 2021-12-08 18-38-44](https://user-images.githubusercontent.com/13064767/145248156-cb7c727a-9763-4c17-9a75-7c8bedf3045d.png)

I don't know from which version It seems like it was ok in v105. 
Now if you press ctrl + LMouse The context menu of the browser and on top of it the menu of the script
Everything is fine in Windows OS

And I also like how the tile design looks on the site https://wallhere.com/
There is no useless padding and generally more useful information fits onto the screen.

![Screenshot from 2021-12-08 18-40-20](https://user-images.githubusercontent.com/13064767/145247564-c3e8bc61-dd84-4a57-b023-d250433604ff.png)

**Comment by ppixiv** [comment]
Does it only happen when clicking zoom buttons, or does it happen for all buttons?

**Comment by raingart** [comment]
the browser context menu is called by clicking on the right mouse button. Most likely not working

I went through all the versions and found out that the problem started appearing with version 104. 103 is working properly

https://greasyfork.org/en/scripts/370418-ppixiv-for-pixiv/diff?v1=980313&v2=978986

Most likely there is a bug somewhere here

![Screenshot from 2021-12-09 11-20-57](https://user-images.githubusercontent.com/13064767/145368791-cbb0bf11-b71c-4802-a09c-2a502ac27e8b.png)

**Comment by ppixiv** [comment]
What Linux distro and WM are you using?  I can try to install it and see what's happening.

**Comment by raingart** [comment]
kenter - Linux pc 5.12.19-3-ck-uksm
wm - xorg-server 21.1.1-3
browser - chrome 89.0.4389.82

can remotely provide access through anydesk

**Comment by ppixiv** [comment]
Try r120.  That WM opens the context menu on mousedown instead of mouseup, so it needs special attention.

**Comment by raingart** [comment]
r120 works correct
