### ISSUE TITLE
[Feature request] Keyboard navigation

### ISSUE THREAD

**Issue by ScrewThisNoise** [ppixiv/ppixiv#36]
Very good script, and pretty much obligatory for actually enjoying Pixiv. Some suggestions for improvement though:
Keyboard shortcut for mouseless browsing: next, previous, next set, previous set, bookmark illust

If possible remapable.

**Comment by ppixiv** [comment]
I've tried to avoid too much input configuration to keep things simple, and the main interface is intended to be with just the mouse.  Here are the hotkeys for those and a few others:

Next/previous page/post: left/right or pgdn/pgup
Next/previous post: shift-left/right
Ctrl-V           - like image
Ctrl-B           - bookmark
Ctrl-Alt-B       - bookmark privately
Ctrl-Shift-B     - remove bookmark
Ctrl-Alt-Shift-M - add bookmark tag
Ctrl-F           - follow
Ctrl-Alt-F       - follow privately
Ctrl-Shift-F     - unfollow
