### ISSUE TITLE
unification url

### ISSUE THREAD

**Issue by raingart** [ppixiv/ppixiv#37]
repalce
```
// @include     http://*.pixiv.net/*
// @include     https://*.pixiv.net/*
```
to
`// @include     http*://*.pixiv.net/*`

**Comment by ppixiv** [comment]
Is there a reason to do this?  I don't want to change the permissions in the script unnecessarily, since it'll cause everybody using it to get a confirmation window warning them that permissions have changed, which I want to keep to a minimum.

**Comment by raingart** [comment]
I'm using Violentmonkey, it doesn't have any warnings.
In general, this is strange behavior because the domain is unchanged.

It doesn't matter. Just so compact and beautiful

**Comment by ppixiv** [comment]
It changes permissions to include anything starting with "http", like "httphellothere://www.pixiv.net".  Even if there are no other matching protocols, it should warn about it.  Anyway, maybe I'll adjust this if there are other permissions to change later (Pixiv doesn't do http anymore at all, it always redirects to https), but I want to avoid annoying users, so I'll leave it alone for now.
