### ISSUE TITLE
Feature Request: Add Booth link on profiles (if available)

### ISSUE THREAD

**Issue by DisasterInbound** [ppixiv/ppixiv#38]
Hello again,

I wanted to know if its possible to add a link for the artist's booth.pm page if they are shown on their profile.

Example: [This artist](https://www.pixiv.net/en/users/1098889) has a section at the bottom of their page with their Booth products and a See All button that directs to the Booth.pm page, screenshot show below. Maybe adding a shortcut to that "see all" link would be enough? What do you think?

(edited to remove non-work-safe image)

**Comment by ppixiv** [comment]
Added in r125.  72480324
