### ISSUE TITLE
[HELP] i dont want the expand manga posts. this is not a complain.

### ISSUE THREAD

**Issue by srishak34** [ppixiv/ppixiv#41]
how do i not expand manga post? is there an option to bring back the separate view? i click one image and then return to page list to get back the separate view, but the problem with this is that i have to load the image, in which many pixiv image has big size file meanwhile me with slow internet connection,  the previous one is obviously better because it loads not the original file/image but only the thumbnail.
could someone please kindly tell me how? if not i would like to reverse the version if its possible?
edit: the dislike with this feature is that, its obstructing the view. the separate view for manga is better just for the sake of it. at least is what i think.
edit2: i cant even ctrl+left-click it. please give an option to do so?
edit3: i have found a way to downgrade it. thanks! will upgrade when things are better.
edit4: there are mangas over 100 pages.... oh gosh, crud, maaaaan i can tell you at least this one thing. IT WAS FREAKING HILARIOUS HAHAHAHAHHAAHA. i literally had to use page up and down that i rarely use. damn that was awesome.

**Comment by ppixiv** [comment]
I've added a button to show a full page search for manga posts.

Please stop spazzing out in tickets.
