### ISSUE TITLE
[Feature Request] Scrollbar on menu.

### ISSUE THREAD

**Issue by srishak34** [ppixiv/ppixiv#42]
Id like to have a scrollbar on this section (menu, look screenshot). my eyesight is bad so i use zoom a lot. because of that, it hinder some of the feature of the tool?(ppxiv) in other words it just become not responsive. in this case it is this, i cant see the search bar.

edit: fyi, the reason why ppixiv gui looks big is because i set the fontsize in chrome option to big.... and the bigness is just not enough for my eyes, so i also zoom in pixiv to 110%.
 
![Screenshot (65)](https://user-images.githubusercontent.com/33346500/171821121-40288bfb-f50c-4863-aec4-0b1350960ce2.png)

**Comment by ppixiv** [comment]
Try r134.  Dropdowns will size to the window, like the bookmark dropdown does.

**Comment by srishak34** [comment]
fixed! thanks so much!
