### ISSUE TITLE
[Feature Request] panning using arrow keys.

### ISSUE THREAD

**Issue by srishak34** [ppixiv/ppixiv#43]
you know what hq/hd images when zoomed in would do right? panning using mouse, left click hold to drag it is just.... tiring to use, to say the least. unless i miss something on how to use this tool. and maybe also make option to set the pan/scroll speed.

**Comment by ppixiv** [comment]
Sorry for the slow reply.  I'm not really sure about this, having to hold down a button and wait for an image to pan seems like it'd be clunky.  It's designed to let you navigate with only the mouse, so you almost never have to use the keyboard unless you're typing in a search or something like that.

I don't understand what you mean by click and drag being tiring, maybe you can explain some more?  (I'd think holding down a key and waiting for it to scroll would be tiring :)  Maybe you're using it differently than I am somehow.

**Comment by srishak34** [comment]
nah not really a slow reply. you see i also made the same suggestion/feature request to other open source application? imageGlass about this feature (they did approve of it, albeit by someone else) but it took a long time, so i expect it would be the same thing over here too.

anyway, having to drag or to scroll using mouse might be more suited to this userscripts intent or purpose. but doing it a lot of time hurt my finger a bit (my index finger). thats what i meant by 'tiring' and also i suppose you wont know the suffering of having a cheap mouse do you? yeahhh about that.... cheap doesnt last long... so all buttons if they were be frequently use like browsing image and stuff, well, **_dragging_**, theyll be gone in a week or month or so. it is their fate.

to counter this problem users like us had to smartly use hotkeys, our keyboard, together with our mouse so that we dont rely on those buttons too much. in this case it is the left mouse button.

although i said all that, im just using barely enough hotkeys to get around so my mouse wont break. so i may miss other things in this userscripts.

**Comment by srishak34** [comment]
i might as well attach it here, see when i do pop menu, there is a _**More...**_ right? there is dropdown there. it doesnt have a scrollbar. it doesnt have it, not in the slightest, when the dropdown menu had so options. just how the heck am i suppose to click the furthest below options if i cant even click it?

![Screenshot (66)](https://user-images.githubusercontent.com/33346500/175803788-a92b40ca-a032-451d-8b72-7c07d7ff127f.png)

**Comment by srishak34** [comment]
oh yeah there is also that one time, when a pixiv work have so many tags the description is just buried. sure the textarea has a scrollbar but if it is already buried what can i even do with it

**Comment by ppixiv** [comment]
I'm focusing on mouse and touchscreen navigation and not keyboard, but newer versions have more robust handling for larger font sizes and smaller windows, so maybe it'll work better for you now.
