### ISSUE TITLE
Never loads at all

### ISSUE THREAD

**Issue by bgiesing** [ppixiv/ppixiv#44]
Get this error in the console every time I load a Pixiv page, ppixiv never loads and there's no icon in the bottom left to toggle to it

`Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid base URL`

![image](https://user-images.githubusercontent.com/7895463/174499345-387bcd44-e48c-453b-9bcd-6b9a22280c2b.png)

I've tried re-installing from scratch with the newest version and same thing. Tried multiple browsers too.

**Comment by ppixiv** [comment]
Thanks, should be fixed in r143.

**Comment by ppixiv** [comment]
Working for you now?

**Comment by bgiesing** [comment]
Yeah it's fixed
