### ISSUE TITLE
[Invalid] I have an issue using virtual numpad arrow keys to go through images

### ISSUE THREAD

**Issue by KculSpam** [ppixiv/ppixiv#46]
I usually use a virtual numpad with arrow keys to go through ppixiv images since my 2-in-1 laptop keyboard keys doesn't work in tablet mode. The arrow keys from the virtual numpad were working on ppixiv yesterday and stopped working today but it is still functional on the regular pixiv website and everywhere else. Is there any way to fix this?

**Comment by ppixiv** [comment]
See if it works for you in r146.

**Comment by KculSpam** [comment]
Ok

**Comment by KculSpam** [comment]
It got fixed. Thanks!
