### ISSUE TITLE
[bug] script shows just a white page in Firefox

### ISSUE THREAD

**Issue by Aigis** [ppixiv/ppixiv#47]
This has been an issue for a few versions but only recently did I have the chance to sit down and confirm it happens with no other extensions running. Enabling ppixiv on Firefox (on both Windows and Linux) results in a blank white page

**Comment by ppixiv** [comment]
It works in my testing, though my version of Firefox is probably out of date (will check that shortly).  Are there any errors in the console (press F12)?  What script manager are you using?

**Comment by Aigis** [comment]
So before I had tested with both Tampermonkey as well as Firemonkey (Firemonkey more recently because I had suspected tampermonkey of a memory leak) and previously both were giving me the same results, but upon reinstalling Tampermonkey and testing it again it appears to be working there again (Could have been a change in the 5-6 versions since I tested there, could have still been something on my end). Not sure why but that's what I get for not re-testing there before opening the ticket, my apologies

**Comment by ppixiv** [comment]
Try to get console logs if it happens again, it shouldn't prevent the page from loading without at least showing an error.
