### ISSUE TITLE
[Feature Request] Pull some more content from the homepage, like Recommended

### ISSUE THREAD

**Issue by yaomtc** [ppixiv/ppixiv#49]
I don't know if this is feasible, but I'd like to see "recommended works" in ppixiv, and for an option to load up ppixiv when I access https://www.pixiv.net/en/

Maybe other sections as well, such as "recommended users" and "recommended illustrations tagged [tag]".

If these aren't feasible to do due to lack of an API or something, maybe instead just have a place to browse works from various tags that aren't necessarily "recommended" but are just the latest or top from that tag

**Comment by yaomtc** [comment]
Never mind, I just found https://www.pixiv.net/discovery and recommended works/users under the "search" hamburger menu button. Thanks!

**Comment by ppixiv** [comment]
You can also right-click an image and use the Similar options from the more options dropdown for image and user-specific suggestions.
