### ISSUE TITLE
[Feature Request] Favorite tags

### ISSUE THREAD

**Issue by PetrK39** [ppixiv/ppixiv#50]
I'd like to be able to pin a tag or several next to a list of tags so that I can quickly access them when viewing users' illustrations.
It would also be convenient for me to be able to apply a specific tag when viewing any user, sort of like a whitelist.

**Comment by ppixiv** [comment]
r152 puts tags in the artist list that are in search history at the top.  It makes it easier to find tags you're interested in, but doesn't need extra UI to edit the list (which helps keep it simple).

Not sure about having a global filter, it's a bit tricky to fit in and probably wouldn't be used much.  It might make sense to have a way to view a filter from a tag search using the tag search you're already on, but Pixiv doesn't support that (you can only view a single tag for an artist, it won't apply a filter like the tag search).  I've thought about having a way to select a tag from an image you're viewing and view that user's posts with that tag, but haven't thought of a clean way to fit it into the UI...
