### ISSUE TITLE
[Bug] No-pan slideshow mode not working

### ISSUE THREAD

**Issue by EeyoreDude** [ppixiv/ppixiv#53]
The setting doesn't seem to change anything, The slideshow pans on both settings.

It's been this way for me for a few months. A few days ago it started working for some reason but when I tried again today it was back to not working. Tried reinstalling the script but that didn't fix it.

Using ppixiv 198 with Tampermonkey v4.18.1 on Firefox 108.0.1.

(Love the script by the way, incredible job)

**Comment by ppixiv** [comment]
Should be fixed in r200.
