### ISSUE TITLE
[Bug] Muted image view override throws error

### ISSUE THREAD

**Issue by EeyoreDude** [ppixiv/ppixiv#54]
Clicking the view image button on a muted image does nothing and throws an error to the console.

Here is the error:
```
Uncaught ReferenceError: helpers is not defined
    ViewerError https://raw.githubusercontent.com/ppixiv/ppixiv/r200/web/vview/viewer/viewer-error.js:25
```

Using ppixiv 200 with Tampermonkey v4.18.1 on Firefox 108.0.1.

**Comment by ppixiv** [comment]
Thanks, should be fixed in r201.
