### ISSUE TITLE
extra indents

### ISSUE THREAD

**Issue by raingart** [ppixiv/ppixiv#55]
https://www.pixiv.net/en/users/22124330/artworks?p=5#ppixiv

![Screenshot_5](https://user-images.githubusercontent.com/13064767/210280872-86499fba-ffc2-483d-9deb-a028b2a89481.png)

**Comment by ppixiv** [comment]
Not seeing that here, what script version and browser version?  (The scrollbar doesn't look like Chrome or Firefox, maybe it's Firefox with a different theme or OS.)

**Comment by raingart** [comment]
oh sure it was a different script
https://greasyfork.org/en/scripts/390077-improve-pixiv-thumbnails

**Comment by raingart** [comment]
i don't like slider in ppixiv

it would be nice if you made such a viewing option as in that script

**Comment by ppixiv** [comment]
r204 has an option for aspect ratio thumbs instead of square.

**Comment by raingart** [comment]
@ppixiv thanks
