### ISSUE TITLE
Opening images in new tab almost always fails

### ISSUE THREAD

**Issue by Rhodan81** [ppixiv/ppixiv#57]
Most of the time when I open an image in a new tab the page now stays completly white, no image no nothing.

Firefox console shows this error:

Uncaught (in promise) TypeError: document.head is null
    _createScript https://raw.githubusercontent.com/ppixiv/ppixiv/r210/web/vview/app-startup.js:848
    _createScript https://raw.githubusercontent.com/ppixiv/ppixiv/r210/web/vview/app-startup.js:760
    load https://raw.githubusercontent.com/ppixiv/ppixiv/r210/web/vview/app-startup.js:721

**Comment by ppixiv** [comment]
(Why did GitHub automatically close this?  I didn't tell it to do that.)

**Comment by ppixiv** [comment]
Thanks, try r211.  It probably depends on settings, but I was only able to see this with ViolentMonkey (not TamperMonkey).

**Comment by Rhodan81** [comment]
r211 fixed it, thanks!
I am using TamperMonkey
