### ISSUE TITLE
All images and thumbnails are broken and not shown up

### ISSUE THREAD

**Issue by Pandaa-P** [ppixiv/ppixiv#58]
All images and thumbnails are broken and not shown up. I use Violentmonkey on Firefox.
Violentmonkey > latest version 
Firefox > latest version 
ppixiv > latest version 

![image](https://user-images.githubusercontent.com/85793213/214416152-8abd299a-fce7-47ed-9302-011e7b3330fe.png)

and the network tab shows this 
![image](https://user-images.githubusercontent.com/85793213/214414691-62416189-fc5f-4917-bf67-75510942eec1.png)

When I disable ppixiv, everything work fine, images and thumbnails shows up and I get the http code 200 in the network tab.

**Comment by ppixiv** [comment]
That looks like an error reaching CloudFlare.  It's a CDN that usually makes things a lot faster for people outside Japan, but it might have had a localized outage (or more likely some internet routing problem).

It should clear up on its own if it's just a network issue, but I'll see if I can add an option to select whether to use CF or not.

**Comment by ppixiv** [comment]
If you're still having problems, try updating to r214 and setting the Pixiv image host to "Pixiv" in the "Other" settings tab.

**Comment by Pandaa-P** [comment]
The update solved the problem. I don't know why ppixiv conflict with CloudFlare tho.
It's wasn't just a network issue on my side, it was on ppixiv side, because when I disable ppixiv all images and thumbnails shows up fine. 

Thank you so much for helping me out ❤️ ❤️ ❤️

**Comment by ppixiv** [comment]
Pixiv's website doesn't use CloudFlare (it might be used for mobile apps), but ppixiv does because it's much faster.  So you won't see problems with CF with regular Pixiv, but it'll be a lot slower unless you're in eastern Asia close to their servers.
