### ISSUE TITLE
Stupid question incoming

### ISSUE THREAD

**Issue by FelixKainz** [ppixiv/ppixiv#6]
What is this?
I just googled "pixiv dark theme" and I found this.
Is this a preset for something like stylish or can it ONLY be used in TamperMonkey and GreaseMonkey? What about normal FireFox?
If it works in normal FF, how do I install it?

Sorry for this stupid question but a media site without a dark theme seems just rediculous to me...

Thanks for your work anyway!

**Comment by ppixiv** [comment]
It's a script, not just a stylesheet.  It's usually installed from here, since it's where updates are released:

https://greasyfork.org/en/scripts/370418-ppixiv-for-pixiv
