### ISSUE TITLE
[Feature request/question] Get link of original illustration

### ISSUE THREAD

**Issue by MarvNC** [ppixiv/ppixiv#60]
If you browse from https://www.pixiv.net/bookmark_new_illust.php or from an artist's page, the original URL to the illustration doesn't display in the URL bar because of ppixiv.  
I was wondering if there is a button/feature to get the original URL of the illustration to share with other people. If not I would like to request a share button that will copy the URL of the illustration when clicked.

**Comment by ppixiv** [comment]
If you hover in the top-left, the illustration title links to the actual image URL.  It'll have #ppixiv at the end (this tells it to keep ppixiv activated if it's clicked), you can remove that if you want.

It looks like the current page number is left in there too, I'll take a look at that when I have a chance. It doesn't really matter, it just makes the URL a bit longer.

**Comment by MarvNC** [comment]
Thank you, I didn't notice that!
