### ISSUE TITLE
Edit muted tags/users

### ISSUE THREAD

**Issue by yaomtc** [ppixiv/ppixiv#61]
I understand that this is held not in the script itself but in some file in the Firefox user data. Where is this? Is it possible to edit it with a text editor? I'm not sure where to look.

**Comment by ppixiv** [comment]
It's _ppixiv_extraMutes in localStorage.  In FF you can view it in DevTools under Storage > Local Storage > pixiv.net and search for "extraMutes".  It's JSON data, not really meant to be edited by hand but you can if you want.

(_ppixiv_extra_mutes is an old name that I changed accidentally a while back, you can ignore it if it's there.)

**Comment by yaomtc** [comment]
I'll give it a try. I recently switched to a new installation and I need to migrate my extra muted tags/users over.

**Comment by ppixiv** [comment]
Get it figured out?

**Comment by ppixiv** [comment]
You should be able to just copy and paste the whole setting between browsers.

**Comment by yaomtc** [comment]
Oh, huh. I had copied the tags into a text file and was thinking of pasting them in... that makes a lot more sense. Thanks.

**Comment by yaomtc** [comment]
That was easy.

I do have both _ppixiv_extra_mutes and _ppixiv_extraMutes, and tags in both. Should I consolidate them?

**Comment by ppixiv** [comment]
Only extraMutes is used.  I renamed that accidentally a while back while fixing some other things and by the time I noticed it seemed like putting it back would just confuse things more.
