### ISSUE TITLE
Not being able to follow accounts through the quick menu

### ISSUE THREAD

**Issue by K0rby** [ppixiv/ppixiv#65]
I don't know if it's just me since if this is an actual bug you since other people should have noticed it by now. But around some months ago I suddenly just cant quick follow accounts by the ppixiv right click menu, but can when I leave the ppixiv (as shown on the imgur gif)
[Imgur](https://imgur.com/UmdopAw)

Can you help me with this?

**Comment by ppixiv** [comment]
Can you update to r217 and see if it works now?

**Comment by K0rby** [comment]
Now it works as it used to, thanks.
