### ISSUE TITLE
[Feature Request] R-18 label on posts

### ISSUE THREAD

**Issue by raeka21** [ppixiv/ppixiv#67]
This might be asking for too much, but could you make the same thing with r-18 like what you did with AI label on AI generated posts? 

You see, the difference between "all ages" and "all" is that, all ages doesn't give much new updates/new stuff/new things, but "all" does. And my pixiv discovery was swarmed with not only AIs but R-18 as well. I kind of want to avoid those, but not by muting the user or tags, since those R-18 can sometimes be a sight for an eyesore, so what I'd like to have is a way to distinct it from the normal posts.

**Comment by raeka21** [comment]
Well, imma just treat this as [Rejected]

**Comment by ppixiv** [comment]
(I just didn't see it, but okay...)
