### ISSUE TITLE
[Bug] This Image Doesn't Display

### ISSUE THREAD

**Issue by MarvNC** [ppixiv/ppixiv#68]
For some reason, this work will not load when using ppixiv version 217.

https://www.pixiv.net/artworks/108377826#ppixiv

**Comment by ppixiv** [comment]
It loads for me 💉, is it just the image not loading (does the image info show up in the corner)?  It might be a CDN problem, you can try changing "Pixiv image host" in the "Other" settings page from CloudFlare to Pixiv to see if it helps.

**Comment by Xeven22** [comment]
Same issue here as well. So many images just refuse to load after the latest update. https://i.imgur.com/66lJUlO.png

**Comment by ppixiv** [comment]
Did you try changing the image host to see if it's a CloudFlare problem?  If that doesn't help, try opening the inspector (press F12), selecting the "Network" tab and check what errors show up.

**Comment by Xeven22** [comment]
May be related to CloudFlare. These are the errors that appear on console:
https://i.imgur.com/OxY6PdV.png
https://i.imgur.com/Axj5tAt.png

**Comment by MarvNC** [comment]
Strangely enough the illustration I originally linked works now after waking up. I did have some rare other images that don't load, but switching the host to Pixiv seems to have fixed the issue.

**Comment by Xeven22** [comment]
Downgrading to v.108 for some reason fixes all errors for me.

**Comment by ppixiv** [comment]
I can't help you if you do that.  Did you try changing the image host in settings like I asked?

**Comment by Xeven22** [comment]
My bad. Changing the image host to "Pixiv" fixed all errors on the latest version. Thank you.

**Comment by ppixiv** [comment]
I've switched the default image host off of CF for now.
