### ISSUE TITLE
[Bug - Minimal Priority] Ranking page is blank when using Safari

### ISSUE THREAD

**Issue by EeyoreDude** [ppixiv/ppixiv#69]
Thanks as always for this script, I seriously use it every day, keep up the great work.

I run this in Safari on my iPhone by saving the main .js file to my phone and running it with the Userscripts app. Works like a charm except for the Ranking page which is blank:
<img src="https://github.com/ppixiv/ppixiv/assets/35280511/ed9d735d-5638-44fd-9769-b6eef303cbd8" width="40%" height="20%">

Here is my bookmarks page working for comparison:
<img src="https://github.com/ppixiv/ppixiv/assets/35280511/fb463121-9527-4618-9341-9afa57b888fc" width="40%" height="20%">

I understand that I'm probably the only person using this on a mobile iOS device though, so don't worry about fixing it unless it seems quick and easy, I don't even really use the ranking page on my phone anyways.

_Edit: made the pictures not massive_

**Comment by ppixiv** [comment]
Try r220.  I've seen that before but I don't use rankings much either, but it's the default page that's shown for the front page so it's worth fixing.

BTW, I'd recommend the oddly-named "Stay" userscripts app, it works a lot more like a standard userscript extension and you can install and update normally from the greasyfork page (or https://ppixiv.org/install).

**Comment by EeyoreDude** [comment]
Switched to Stay with v220 and it works great!

**Comment by ppixiv** [comment]
By the way, did navigation and pan/zoom make sense when you started using it on mobile?  The touch-and-drag vs. drag-quickly gestures are a bit unusual and I don't know if it makes sense to people at first.  (But I tried a bunch of different styles of navigation and it's the best way I found.  Swiping from the edge would be better, but it doesn't work well in browsers.)
