### ISSUE TITLE
Search page not working

### ISSUE THREAD

**Issue by otomn** [ppixiv/ppixiv#7]
Search will always return no result. Tried to debug it myself, it appears that they are using a new search result page. New request api is "https://www.pixiv.net/ajax/search/artworks/hi?word=hi" for searching keyword "hi"

**Comment by ppixiv** [comment]
I'm not seeing that yet.  Sometimes they do staged rollouts (some people see updates before others), which can be tricky.  Can you give me a URL to an actual search page rather than the API?  Maybe that'll let me see it.

**Comment by otomn** [comment]
Like this? https://www.pixiv.net/search.php?word=hi#ppixiv

**Comment by otomn** [comment]
Also if you logout you can see the js-mount-point again

**Comment by ppixiv** [comment]
I just get the old search there.  What happens if you go to another page first, like bookmarks, and search from the menu, instead of Pixiv's search box?  That doesn't actually load the search page, only the API endpoint, so I wonder if that works.

**Comment by otomn** [comment]
Sadly same as before

**Comment by ppixiv** [comment]
Try updating to r59, should be working now.

**Comment by otomn** [comment]
Thanks.
