### ISSUE TITLE
Why was the scrollbar disabled?

### ISSUE THREAD

**Issue by raeka21** [ppixiv/ppixiv#72]
That thing is actually useful you know? Otherwise I wont know how far below I've been in the page.

Or was it just me that's having this issue?

this is on ver 222, I downgraded to ver 221 just in case.

**Comment by ppixiv** [comment]
It's related to working around some stuff that browsers broke lately.  I'll take another look when I have a chance.

**Comment by ppixiv** [comment]
https://github.com/ppixiv/ppixiv/commit/e5ba8a2c9435fe08348a202fd04cd074fa40a94c
