### ISSUE TITLE
[Feature Request]  Group tagging

### ISSUE THREAD

**Issue by EeyoreDude** [ppixiv/ppixiv#73]
Loving the script as always.

I would love a group tagging feature similar to how the feature functions on Pixiv's base bookmarks page.

Here's the feature I'm talking about:

https://github.com/ppixiv/ppixiv/assets/35280511/27c2197b-4c5d-4f67-b66a-a3cd46bf50b2

**Comment by ppixiv** [comment]
I've used that, it just seems like a bit of a one-off (when you first start using tags or want to rename a tag, etc).  I don't know if duplicating Pixiv's UI would be much better than what they already have, at least for the amount of work it'd take...

**Comment by EeyoreDude** [comment]
Yeah, that makes sense. Not really a reason to recreate it if the original is fine.
