### ISSUE TITLE
Auto-google translate by Right-click and translate to english

### ISSUE THREAD

**Issue by raeka21** [ppixiv/ppixiv#74]
Do you have any idea why the page just snapped everytime I did that? Or was it just me.... this used to work some versions ago, but now it didn't.

I'm just mentioning it here in case you wanted to fix it and if it wasn't just me, but it's also okay to reject it.

**Comment by ppixiv** [comment]
It seems to work for me in Chrome and Edge.

**Comment by raeka21** [comment]
must be me only then
