### ISSUE TITLE
[Feature Request] Reverse image order

### ISSUE THREAD

**Issue by u3shit** [ppixiv/ppixiv#76]
Would it be possible to reverse the order of the pictures, or at least make separate shortcuts to change between manga pages and posts like on vanilla pixiv? ppixiv flattens manga illustrations into the reverse chronological order posts, ending up with a weird mixed-endian order.
Right now to browse through a user's works through ppixiv is very cumbersome: first select an image on the users profile, if it's a manga, press down (or mouse wheel) until you reach the next (older) post. The only reliable way to tell this at the moment is to watch when you end up with `page=1` at the end of the URL bar, so fullscreen mode is out of question. When you're here, press up, home, up, home (the last home can be skipped if you're already on page=1), press down to look at the pages, and repeat from the beginning. In vanilla pixiv I can just press down to go to the next manga page, and left to go to the next post (and even easily skip a manga with left if it is not interesting, and pressing up/down doesn't change posts).

**Comment by ppixiv** [comment]
I don't entirely follow, posts are in natural order (newest posts first, manga posts start to end), but I've added a sort option to view an artist starting at the end.  You can also shift-mousewheel to skip manga pages and go to the next or previous post, or open the corner hover which shows the current page as a red bar at the bottom along withi the page number.

**Comment by u3shit** [comment]
> I don't entirely follow

Well, when I find a new artist I usually like to go from older works to newer (sometimes newer works build upon older ones, for example multi part manga), but inside mangas you still need to go from first page to last.

> I've added a sort option to view an artist starting at the end

Thanks, it looks good.

> shift-mousewheel to skip manga pages

Cool, I didn't know about it. Maybe it should be mentioned in the readme?

> which shows the current page as a red bar at the bottom along withi the page number

Yes, I know about it, but it's not normally visible unless you hover it.
