### ISSUE TITLE
[Bug]: _ppixiv_zoom-mode not restored globally after stopping slideshow

### ISSUE THREAD

**Issue by EnergoStalin** [ppixiv/ppixiv#82]
It stays on locked which breaks normal viewing

To reproduce start slideshow and cancel it from right click menu unchecking slideshow toggle it will restore mode for current image and subsequent ones but when reopen image from listing page it breaks because global **_ppixiv_zoom-mode** in **local storage** not restored to normal

**Comment by ppixiv** [comment]
The zoom mode is just being changed at an odd time, you can still zoom out normally.  r230 should fix it so slideshow mode doesn't change the zoom level (panning mode will though).

**Comment by EnergoStalin** [comment]
Thanks!
