### ISSUE TITLE
Content-Security-Policy blocked userscript

### ISSUE THREAD

**Issue by DmitriyPekar** [ppixiv/ppixiv#87]
browser: librewolf

**Comment by DmitriyPekar** [comment]
CSP is used when you use userscript

**Comment by ppixiv** [comment]
I don't know what you mean.  CSP is a security feature used by some sites (mostly sites that process payments), but I haven't seen Pixiv use it anywhere.  What page on the site, and which userscript manager?  Do you see this problem in Chrome or Firefox, using TamperMonkey or ViolentMonkey?  I don't see this happening, so I can't help without concrete information.

**Comment by DmitriyPekar** [comment]
> I don't know what you mean. CSP is a security feature used by some sites (mostly sites that process payments), but I haven't seen Pixiv use it anywhere. What page on the site, and which userscript manager? Do you see this problem in Chrome or Firefox, using TamperMonkey or ViolentMonkey? I don't see this happening, so I can't help without concrete information.


Violentmonkey, Browser librewolf fork of firefox, any page

**Comment by DmitriyPekar** [comment]
with the script, any page looks like this

![изображение](https://github.com/ppixiv/ppixiv/assets/14822106/f0b3f1b0-20ba-4107-9aa7-4e47753847d3)

**Comment by DmitriyPekar** [comment]
solved the problem by turning off privacy possum
