### ISSUE TITLE
Add an option to disable the right click menu

### ISSUE THREAD

**Issue by satyrsaw** [ppixiv/ppixiv#88]
Basically the title, just think it would be nice to be able to disable that menu.

Or when viewing the img add it as a menu on the side, so that we can use the default browser right click of the img

**Comment by ppixiv** [comment]
I'd rather not add major variations on the UI style since it's a hassle to maintain, but you can shift-right-click to get the browser context menu.  There's also the "Shift-right-click to show the popup menu" in options to switch them (this isn't available in Firefox).

**Comment by satyrsaw** [comment]
Oh I see, thanks for letting me know.
