### ISSUE TITLE
New feature discussion

### ISSUE THREAD

**Issue by amdost** [ppixiv/ppixiv#9]
I am also working on a new filter function which allows filtering on any search page with syntax like:
"filter:width > 800 && height > 1000 && !bookmarked"
I have pushed an early prototype version to my master branch if you want to take a look. So far the input box is the same as the search box, and the output is just console.log for any info or error. Which, tbh, is not so user friendly.
If interested we can create a new dev branch and talk about how we can better integrate the new feature.

**Comment by ppixiv** [comment]
One thing I want to be careful of is to that, if a lot of images are being hidden, it doesn't spam the site with API calls.  If a user uses a search that's too specific, and 1 in 20 images matches, it'd be easy for it to spam dozens or hundreds of page requests trying to fill the screen.  That's one reason I've hesitated doing things like client-side mutes.  It's possible to solve this by having it stop and go "click here to load more images" if it would load more than a couple pages of data without the user scrolling, but I'd need to figure out how to do that without making the scroll loading logic brittle.

My main hesitation with this sort of filtering is that while these searches can be really useful, they really want to be server-side.  I have countless thousands of bookmarks, and if I could filter by image tags, aspect ratio, etc. in them it would be incredibly useful.  But when it can only do it page by page, it would end up just saying "click again... now click again..." as it slowly goes through hundreds of pages one at a time, and I have a feeling that would happen a lot.

That said, I like the "tag filter" syntax for this sort of filtering.  Danbooru and Gmail both use this.  They're single words, so you have searches like

width:>800 height:>800
width:800..1500 bookmarked:false

The nice thing about that is it stays space-delimited.  That makes it easy to parse and understand, and it fits in naturally with tags/keywords in the same search.

**Comment by amdost** [comment]
Thanks for the tips.

**Comment by ppixiv** [comment]
I don't think client-side search filters are the way to go, it's the sort of thing that needs to be done server-side.  Of course if Pixiv adds more powerful searching I'll support it as well.
