### ISSUE TITLE
HTTP 500 in Cotrans requests with FireMonkey

### ISSUE THREAD

**Issue by Katzenwerfer** [ppixiv/ppixiv#99]
Testing out scripts with FireMonkey I noticed Cotrans translations don't work.
The console spits out an HTTP 500 error whenever a request is done to the API.

**Comment by ppixiv** [comment]
This looks like a bug in FireMonkey.  It's missing ArrayBuffer handling for FormData.  This works in other script managers, so I've filed a bug.  In the meantime, for Firefox this does work with ViolentMonkey.

erosman/support#633

**Comment by ppixiv** [comment]
I'm getting 500s from all translators now.  I have a feeling it's abandoned, the maintainer hasn't been active for almost a year... 
 Should work now if it comes back up, though.

**Comment by EnergoStalin** [comment]
Apparently [this](https://github.com/ppixiv/ppixiv/commit/9997a1dc5ea1eb3b2f1d4e793edf49556e2eb00c) commit breaking things for me with it filtered out i didn't get 500 statuses. Btw i'm on latest firefox with tampermonkey as script manager.

**Comment by ppixiv** [comment]
Will take another look, thanks.

**Comment by ppixiv** [comment]
Try r238.
